### ISSUE TITLE
Entity application needs an endpoint to expose driver types

### ISSUE THREAD

**Issue by aalpern** [clusto/clusto-apiserver#10]
Various entity endpoints, such as `/entity/<driver>/` (see https://github.com/clusto/clusto-apiserver/blob/master/clustoapi/apps/entity.py#L29) accept a clusto _driver_ name as a parameter, and they validate that it's a valid driver now. However, there is no endpoint to list what the known drivers are. 

The closest is to call the `/entity` endpoint, which lists the name of every entity in the system, and parse out each string. They're all of the form `/<drivername>/<entityname>`. That only lists entities that actually exist, however, so it may not be complete. 

A simple endpoint that exposes `clusto.driverlist` (see [usage](https://github.com/clusto/clusto-apiserver/blob/master/clustoapi/apps/entity.py#L75)) - say, `/entity/drivers`, or just `/drivers` - would do the trick.

**Comment by JTCunning** [comment]
IMO, adding a ``/driverlist`` endpoint to ``server.py`` coincides with the current methods that live in there, methods that come from the base clusto module.

**Comment by aalpern** [comment]
:+1:

**Comment by thekad** [comment]
I wish closing the PR would close this one
